name: CI/CD Pipeline

on:
  push:
    branches:
      - cpclass-ansible-cicd

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Ansible 
      run: pip install ansible

    - name: Run playbook to install nginx and deploy code
      run: ansible-playbook -i inventory ansible-cicd-playbook.yml